---
title: "Modeling SOC with Random Forest"
author: "Anthony Stewart"
output:
  html_document:
    df_print: paged
    theme: readable
---

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

h1, h3, h4 {
  text-align: center;
}
```


```{r setup, include=FALSE}
library(formatR)
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", fig.show = "hold", time_it = TRUE, dpi = 100, message = FALSE, warning = FALSE, results = "hide", tidy.opts = list(width.cutoff = 60), tidy = T, collapse = TRUE)

library(car)
library(dplyr)
library(tidyr)
library(stringr)
library(stats)
library(pdp)
library(vip)
library(formatR)
library(grid)
library(gridExtra)
library(ppcor)
library(randomForest)
library(quantregForest)
library(ranger)
library(mlr3)
library(mlr3pipelines) 
library(mlr3tuning)
library(mlr3learners)
library(mlr3extralearners)
library(mlr3viz)
library(mlr3fselect)
library(iml)
library(kernelshap)
library(shapviz)
library(here)
here()

rgl::setupKnitr(autoprint = TRUE)

set.seed(11)
```

```{r include=FALSE}

# Quick R^2 function
r.sq <- function(y,y.fitted){
    res <- y-y.fitted
    1-sum(res^2)/sum((y-mean(y))^2)
}
```


```{r}
pnw_dat <- read.csv(here("data/dataframes/PNW_data_MLR3_RFM_LMM.csv")) |>
  dplyr::select(-site, -X) |>
  dplyr::mutate(across(where(is.character), as.factor))
train <- read.csv(here("data/dataframes/Train_data.csv")) |> 
  dplyr::select(-site, -X) |> 
  dplyr::mutate(across(where(is.character), as.factor),
                geomorphons = factor(geomorphons, levels = levels(pnw_dat$geomorphons)),
                nlcd_reclass = factor(nlcd_reclass, levels = levels(pnw_dat$nlcd_reclass)))
test <- read.csv(here("data/dataframes/Test_data.csv")) |> 
  dplyr::select(-site, -X) |> 
  dplyr::mutate(across(where(is.character), as.factor),
                geomorphons = factor(geomorphons, levels = levels(pnw_dat$geomorphons)),
                nlcd_reclass = factor(nlcd_reclass, levels = levels(pnw_dat$nlcd_reclass)))
test.wet <- read.csv(here("data/dataframes/RFM_Test_Wet_data.csv")) |> 
  dplyr::select(-site, -X) |> 
  dplyr::mutate(across(where(is.character), as.factor),
                geomorphons = factor(geomorphons, levels = levels(pnw_dat$geomorphons)),
                nlcd_reclass = factor(nlcd_reclass, levels = levels(pnw_dat$nlcd_reclass)),
                LITH = factor(LITH, levels = levels(pnw_dat$LITH)))
test.upl <- read.csv(here("data/dataframes/RFM_Test_Upl_data.csv")) |> 
  dplyr::select(-site, -X) |> 
  dplyr::mutate(across(where(is.character), as.factor),
                geomorphons = factor(geomorphons, levels = levels(pnw_dat$geomorphons)),
                nlcd_reclass = factor(nlcd_reclass, levels = levels(pnw_dat$nlcd_reclass)),
                LITH = factor(LITH, levels = levels(pnw_dat$LITH)))

# glimpse(pnw_dat)
# glimpse(train) 
# glimpse(test)
```


## MLR3 Package 

```{r}
set.seed(11)
RF_task_nw <- mlr3::as_task_regr(train, target = "SOC_stock_spline", id = "rfm")
RF_task_nw$set_col_roles("sample_ID", "group")
# RF_task_nw$feature_names
to_remove_nw <- RF_task_nw$feature_names[str_detect(RF_task_nw$feature_names, "_1000|_300|_50|nlcd|WIP")]
RF_task_nw$select(dplyr::setdiff(RF_task_nw$feature_names, to_remove_nw))
RF_task_nw$feature_names
```


```{r}
#| eval: false

instance_nw = fsi(
  task = RF_task_nw,
  learner = lrn("regr.ranger", importance = "permutation"),
  resampling = rsmp("repeated_cv", folds = 5, repeats = 10),
  measures = msr("regr.rmse"),
  terminator = trm("none"),
  store_models = TRUE
)

fselector_nw = fs("rfe",
               n_features = floor(0.5*ncol(train)),
               feature_number = 2,
               aggregation = "rank")
fselector_nw$optimize(instance_nw)

#as.data.table(instance$archive)

instance_nw$archive$best()

instance_nw$result_feature_set
instance_nw$result_y
instance_nw$result

saveRDS(instance_nw, file = "analysis/models/MLR3_RecursiveFeat_Stocks_nw_noWIP.rds" |> here())
```



```{r}
instance_nw <- readRDS(here("analysis/models/MLR3_RecursiveFeat_Stocks_nw_noWIP.rds"))
RF_task_nw$select(instance_nw$result_feature_set)
RF_lrn_nw <- lrn("regr.ranger",
              num.trees = to_tune(c(1000, 2000)),
              mtry = to_tune(c(2, 4, 8, length(RF_task_nw$feature_names))), 
              max.depth = to_tune(c(4,8,16,24)),
              min.node.size = 2, #to_tune(c(1,4,8,12)),
              importance = "permutation",
              quantile_response = 0.5,
              quantiles = c(0.025, 0.5, 0.975))
RF_lrn_nw$predict_type = "quantiles"


tune_instance_nw <- ti(task = RF_task_nw,
                    learner = RF_lrn_nw,
                    resampling = rsmp("cv", folds = 10),
                    measures = msrs(c("regr.rmse")),
                    terminator = trm("none"))
```


```{r}
#| eval: false
tuner_nw = mlr3tuning::tnr("grid_search", resolution = 5, batch_size = 5)
tuner_nw$param_set
tuner_nw$optimize(tune_instance_nw)
tune_instance_nw$result$learner_param_vals
tuner_nw$print()

saveRDS(tune_instance_nw, file = here("analysis/models/MLR3_RFM_Ranger_tune_instance_nw_noWIP.rds" ))
```



```{r}
#| eval: false
tune_instance_nw <- readRDS(file = here("analysis/models/MLR3_RFM_Ranger_tune_instance_nw_noWIP.rds"))
RF_lrn_nw_tuned = lrn("regr.ranger")
RF_lrn_nw_tuned$param_set$values = tune_instance_nw$result_learner_param_vals[[1]]
RF_lrn_nw_tuned$param_set$values$num.threads <- 1
RF_lrn_nw_tuned$param_set$values$keep.inbag <- TRUE  # <- REQUIRED for ranger quantile regression; set AFTER the param-set overwrite so it survives
RF_lrn_nw_tuned$predict_type      = "quantiles"
RF_lrn_nw_tuned$quantiles         <- c(0.025, 0.5, 0.975)  # in current mlr3learners these are R6 fields, NOT lrn() args
RF_lrn_nw_tuned$quantile_response <- 0.5
set.seed(11)
RF_lrn_nw_tuned$train(RF_task_nw)$model

saveRDS(RF_lrn_nw_tuned, here("analysis/models/MLR3_RFM_Ranger_tuned_noWIP.rds"))


```

```{r}
RF_lrn_nw_tuned <- readRDS(here("analysis/models/MLR3_RFM_Ranger_tuned_noWIP.rds"))
RF_lrn_nw_tuned$model
```


Resampling
```{r}
#| eval: false

set.seed(11)
RF_lrn_nw_tuned <- readRDS("analysis/models/MLR3_RFM_Ranger_tuned_noWIP.rds" |> here())

RF_CV_nw <- rsmp("repeated_cv", repeats = 10, folds = 10)

RF_rr_nw <- mlr3::resample(RF_task_nw, RF_lrn_nw_tuned, RF_CV_nw)
saveRDS(RF_rr_nw, file = "analysis/models/MLR3_RFM_Ranger_resampling_noWIP.rds" |> here())
```


```{r}
RF_rr_nw <- readRDS(file = here("analysis/models/MLR3_RFM_Ranger_resampling_noWIP.rds"))
RF_rr_nw_acc <- RF_rr_nw$score(msrs(c("regr.rmse", "regr.mse", "regr.rsq")))
RF_rr_nw_acc[, .(iteration, regr.rmse, regr.mse, regr.rsq)]
RF_rr_nw$aggregate(msrs(c("regr.rmse", "regr.mse", "regr.rsq")))
autoplot(RF_rr_nw, measure = msr("regr.rsq"), type = "histogram")
autoplot(RF_rr_nw, measure = msr("regr.rmse"), type = "histogram")


write_csv(RF_rr_nw_acc, file = "data/dataframes/MLR3_RFM_Ranger_tuned_CV_results_noWIP.csv" |> here())
```


```{r}
RF_rr_nw_acc <- read.csv(here("data/dataframes/MLR3_RFM_Ranger_tuned_CV_results_noWIP.csv"))

measures <- msrs(c("regr.rmse", "regr.mse", "regr.rsq"))
RF_lrn_nw_tuned$predict_newdata(test)$score(measures)
RF_lrn_nw_tuned$predict_newdata(test.wet)$score(measures)
RF_lrn_nw_tuned$predict_newdata(test.upl)$score(measures)
plot(RF_lrn_nw_tuned$predict_newdata(test))
plot(RF_lrn_nw_tuned$predict_newdata(test.wet))
plot(RF_lrn_nw_tuned$predict_newdata(test.upl))


tdf_nw <- data.frame(truth = RF_lrn_nw_tuned$predict_newdata(test)$truth,
           predict = RF_lrn_nw_tuned$predict_newdata(test)$response)
write_csv(tdf_nw, here("data/dataframes/PNW_SOC_RF_noWIP_test_pred_response.csv"))
ggplot() +
  geom_point(aes(x = tdf_nw$truth, y = tdf_nw$predict)) +
  geom_abline(intercept = 0, slope = 1) +
  ylim(0, 4) + 
  xlim(0, 4)


caret::R2(pred = tdf_nw$predict,obs = tdf_nw$truth, form = "traditional")
```


### Shapley values 


```{r}
#| eval: false
#| message: false

pnw_dat_select <- pnw_dat |> 
    dplyr::select(dplyr::all_of(RF_task_nw$feature_names))
pnw_dat_select_wet <- pnw_dat |> filter(WIP >= 0.50) |>
    dplyr::select(dplyr::all_of(RF_task_nw$feature_names))
pnw_dat_select_upl <- pnw_dat |> filter(WIP < 0.50) |>
    dplyr::select(dplyr::all_of(RF_task_nw$feature_names))
train_select <- train |>
    dplyr::select(dplyr::all_of(RF_task_nw$feature_names))


rtbx_nw <- pnw_dat_select[sample(nrow(pnw_dat_select), size = 200), ]
rtbx_nw_wet <- pnw_dat_select_wet[sample(nrow(pnw_dat_select_wet), size = 100),]
rtbx_nw_upl <- pnw_dat_select_upl[sample(nrow(pnw_dat_select_upl), size = 100),]

ks_nw <- kernelshap(object = RF_lrn_nw_tuned$model, X = rtbx_nw, bg_X = train_select, parallel = T, )
ks_nw

ks_nw_wet <- kernelshap(object = RF_lrn_nw_tuned$model, X = rtbx_nw_wet, bg_X = train_select, parallel = T)
ks_nw_wet

ks_nw_upl <- kernelshap(object = RF_lrn_nw_tuned$model, X = rtbx_nw_upl, bg_X = train_select, parallel = T)
ks_nw_upl

saveRDS(ks_nw, file = "analysis/models/MLR3_RFM_Ranger_KernelShap_noWIP.rds" |> here())
saveRDS(ks_nw_wet, 
        file = "analysis/models/MLR3_RFM_Ranger_KernelShap_Wet_noWIP.rds" |> here())
saveRDS(ks_nw_upl, 
        file = "analysis/models/MLR3_RFM_Ranger_KernelShap_Upl_noWIP.rds" |> here())
```

```{r}
ks_nw <- readRDS(file = "analysis/models/MLR3_RFM_Ranger_KernelShap_noWIP.rds" |> here())
ks_nw_wet <- readRDS(file = "analysis/models/MLR3_RFM_Ranger_KernelShap_Wet_noWIP.rds" |> here())
ks_nw_upl <- readRDS(file = "analysis/models/MLR3_RFM_Ranger_KernelShap_Upl_noWIP.rds" |> here())
sv_importance(shapviz(ks_nw))
sv_importance(shapviz(ks_nw_wet))
sv_importance(shapviz(ks_nw_upl))
```


```{r}
ks_nw_vars <- ks_nw$S |> as.data.frame() |> dplyr::summarise(across(everything(), ~sum(abs(.x)))) |> pivot_longer(everything(), names_to = "column", values_to = "abs_sum") %>%
    arrange(desc(abs_sum)) %>%
    slice_head(n = 5)
ks_nw_wet_vars <- ks_nw_wet$S |> as.data.frame() |> dplyr::summarise(across(everything(), ~sum(abs(.x)))) |> pivot_longer(everything(), names_to = "column", values_to = "abs_sum") %>%
    arrange(desc(abs_sum)) %>%
    slice_head(n = 5)
ks_nw_upl_vars <- ks_nw_upl$S |> as.data.frame() |> dplyr::summarise(across(everything(), ~sum(abs(.x)))) |> pivot_longer(everything(), names_to = "column", values_to = "abs_sum") %>%
    arrange(desc(abs_sum)) %>%
    slice_head(n = 5)

sv_dependence(shapviz(ks_nw), v = c(ks_nw_vars$column[1], ks_nw_vars$column[2], ks_nw_vars$column[3], ks_nw_vars$column[4]), color_var = ks_nw_vars$column[5])
sv_dependence(shapviz(ks_nw_wet), v = c(ks_nw_wet_vars$column[1], ks_nw_wet_vars$column[2], ks_nw_wet_vars$column[3], ks_nw_wet_vars$column[4]), color_var = ks_nw_wet_vars$column[5])
sv_dependence(shapviz(ks_nw_upl), v = c(ks_nw_upl_vars$column[1], ks_nw_upl_vars$column[2], ks_nw_upl_vars$column[3], ks_nw_upl_vars$column[4]), color_var = ks_nw_upl_vars$column[5])
```


```{r}
#| eval: false

library(iml)
RF_task_nw_feats <- RF_task_nw$data(cols = RF_task_nw$feature_names)
RF_task_nw_target <- RF_task_nw$data(cols = RF_task_nw$target_names)

predictor_nw <- iml::Predictor$new(RF_lrn_nw_tuned,
                                data = RF_task_nw_feats, 
                                y = RF_task_nw_target)
saveRDS(predictor_nw, "analysis/models/MLR3_Predictor_noWIP.rds" |> here())



ia_nw_1 <- Interaction$new(predictor_nw, feature = ks_nw_vars$column[1])
ia_nw_2 <- Interaction$new(predictor_nw, feature = ks_nw_vars$column[2])
ia_nw_3 <- Interaction$new(predictor_nw, feature = ks_nw_vars$column[3])
ia_nw_4 <- Interaction$new(predictor_nw, feature = ks_nw_vars$column[4])
ia_nw_5 <- Interaction$new(predictor_nw, feature = ks_nw_vars$column[5])

saveRDS(ia_nw_1, 
        file = "writing/Figures/MLR3_RFM_Interact_1_plot_noWIP.rds" |> here())
saveRDS(ia_nw_2, 
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_2_plot_noWIP.rds" |> here())
saveRDS(ia_nw_3, 
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_3_plot_noWIP.rds" |> here())
saveRDS(ia_nw_4, 
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_4_plot_noWIP.rds" |> here())
saveRDS(ia_nw_5, 
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_5_plot_noWIP.rds" |> here())
```


```{r}

ia_nw_1 <- readRDS(
        file = "writing/Figures/MLR3_RFM_Interact_1_plot_noWIP.rds" |> here())
ia_nw_2 <- readRDS(
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_2_plot_noWIP.rds" |> here())
ia_nw_3 <- readRDS( 
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_3_plot_noWIP.rds" |> here())
ia_nw_4 <- readRDS(
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_4_plot_noWIP.rds" |> here())
ia_nw_5 <- readRDS( 
        file = "writing/Figures/MLR3_RFM_Ranger_Interact_5_plot_noWIP.rds" |> here())

# ia_nw_depth$results |> data.frame() |> dplyr::mutate(.feature = factor(.feature)) |>
#   dplyr::mutate(.feature = fct_reorder(.feature, desc(.interaction))) |>
#   dplyr::mutate(.feature = case_when(
#                               str_detect(.feature, "lower_depth") ~
#                                 str_replace_all(.feature, "lower_depth", "Depth"),
#                               str_detect(.feature, "LITH:") ~
#                                 str_replace_all(.feature, "LITH:", "Lithology "),
#                               )
#          ) 
# ia_nw_map$results <- ia_nw_map$results |> dplyr::mutate(.feature = factor(.feature)) |>
#   dplyr::mutate(.feature = fct_reorder(.feature, desc(.interaction)))
# ia_nw_wip$results <- ia_nw_wip$results |> dplyr::mutate(.feature = factor(.feature)) |>
#   dplyr::mutate(.feature = fct_reorder(.feature, desc(.interaction)))
# ia_nw_grad$results <- ia_nw_grad$results |> dplyr::mutate(.feature = factor(.feature)) |>
#   dplyr::mutate(.feature = fct_reorder(.feature, desc(.interaction)))



ia_nw_1_plot <- plot(ia_nw_1)
ia_nw_2_plot <- plot(ia_nw_2)
ia_nw_3_plot <- plot(ia_nw_3)
ia_nw_4_plot <- plot(ia_nw_4)
ia_nw_5_plot <- plot(ia_nw_5)

ia_nw_1_plot 
ia_nw_2_plot 
ia_nw_3_plot 
ia_nw_4_plot 
ia_nw_5_plot 

saveRDS(ia_nw_1_plot, file = "writing/Figures/MLR3_RFM_Interact_1_plot_noWIP.rds" |> here())
saveRDS(ia_nw_2_plot, file = "writing/Figures/MLR3_RFM_Interact_2_plot_noWIP.rds" |> here())
saveRDS(ia_nw_3_plot, file = "writing/Figures/MLR3_RFM_Interact_3_plot_noWIP.rds" |> here())
saveRDS(ia_nw_4_plot, file = "writing/Figures/MLR3_RFM_Interact_4_plot_noWIP.rds" |> here())
saveRDS(ia_nw_5_plot, file = "writing/Figures/MLR3_RFM_Interact_5_plot_noWIP.rds" |> here())
```


```{r}
m_nw <- RF_lrn_nw_tuned$model 
p_nw <- m_nw$model$predictions
t_nw <- RF_task_nw$truth()
w_nw <- RF_task_nw$data(cols = "WIP")$WIP

oob_tbl_nw <- tibble(truth = t_nw, pred = p_nw, wip = w_nw)

oob_metrics_subset_wet_nw <- oob_tbl_nw |>
  filter(wip >= 0.5) |>
  summarise(
    rmse = sqrt(mean((truth - pred)^2)),
    r2   = 1 - sum((truth - pred)^2) / sum((truth - mean(truth))^2)
  )  |> 
  mutate(LandscapeClass = "WET")
oob_metrics_subset_upl_nw <- oob_tbl_nw |>
  filter(wip < 0.5) |>
  summarise(
    rmse = sqrt(mean((truth - pred)^2)),
    r2   = 1 - sum((truth - pred)^2) / sum((truth - mean(truth))^2)
  ) |> 
  mutate(LandscapeClass = "UPL")

oob_err_wetupl_nw <- bind_rows(oob_metrics_subset_wet_nw, oob_metrics_subset_upl_nw) |> 
  dplyr::select(LandscapeClass, everything())

qrf.train_nw <- RF_lrn_nw_tuned$predict_newdata(train)$response

qrf.test_nw <- RF_lrn_nw_tuned$predict_newdata(test)$response
qrf.wet.test_nw <- RF_lrn_nw_tuned$predict_newdata(test.wet)$response
qrf.upl.test_nw <- RF_lrn_nw_tuned$predict_newdata(test.upl)$response


plot(qrf.wet.test_nw, test.wet$SOC_stock_spline) + abline(0,1)

r.sq(y.fitted = qrf.test_nw, y = test$SOC_stock_spline)

```


```{r}
qrf_errdf_nw <- data.frame("LandscapeClass" = c("Full", "Wetland", "Upland"), 
    "RFM.R2_OOB" = c(
      RF_lrn_nw_tuned$model$model$r.squared,
      oob_err_wetupl_nw$r2[[1]],
      oob_err_wetupl_nw$r2[[2]]
      ),
    "RFM.RMSE_OOB" = c(
      sqrt(RF_lrn_nw_tuned$model$model$prediction.error),
      oob_err_wetupl_nw$rmse[[1]],
      oob_err_wetupl_nw$rmse[[2]]
      ),
    "RFM.R2_test" = c(r.sq(y.fitted = qrf.test_nw, y = (test$SOC_stock_spline)),
                      r.sq(y.fitted = qrf.wet.test_nw, y = (test.wet$SOC_stock_spline)),
                      r.sq(y.fitted = qrf.upl.test_nw, y = (test.upl$SOC_stock_spline))),
    "RFM.RMSE_test" = c(caret::postResample(pred = qrf.test_nw, 
                                            obs = (test$SOC_stock_spline))[[1]],
                      caret::postResample(pred = qrf.wet.test_nw, 
                                          obs = (test.wet$SOC_stock_spline))[[1]],
                      caret::postResample(pred = qrf.upl.test_nw, 
                                          obs = (test.upl$SOC_stock_spline))[[1]])
    )
qrf_errdf_nw |> flextable::flextable()

readr::write_csv(qrf_errdf_nw, file = "data/dataframes/MLR3_RFM_ErrorDF_noWIP.csv" |> here())
```


```{r}

```

